version: '3'
services:
  api:
    build:
      context: ./backend
    container_name: api
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-api
    ports:
      - '3001:3001'
  ui:
    build:
      context: ./frontend
    container_name: ui
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-ui
    ports:
      - '3000:3000'
  nginx:
    container_name: nginx
    depends_on:
      - ui
      - api
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-nginx
    ports:
      - '80:80'
    build:
      context: ./nginx
